
import { Button } from './components/ui/button'
import { Textarea } from './components/ui/textarea'

export function App() {

  return (
    <div className='flex flex-col min-h-screen'>
      <header className='border-b flex items-center justify-between px-6 py-3'>Header</header>
      <main className='flex flex-1 gap-6 p-6'>
        <aside>
            Menu
        </aside>

        <section
          className='flex flex-col flex-1 gap-4'
        >
          <div className='flex-1 gap-4 grid grid-rows-2'>
            <Textarea
              className='leading-relaxed p-4 resize-none'
              placeholder='Type your instructions for AI here or select on the side menu a pre-defined prompt (Title or Description)!'
            />
            <Textarea
              className='leading-relaxed p-4 resize-none'
              placeholder='The result generated by AI using the instructions above will be shown here...'
              readOnly
            />
          </div>
          <p className='italic text-muted-foreground text-sm'>
            Remember: you can use the<code className='text-indigo-600'>
              {' {transcription} '}</code>variable in your prompt to add a transcription content to uploaded video!
          </p>
        </section>
      </main>
      <Button>Click me</Button>
    </div>
  )
}
