
import { Button } from './components/ui/button'
import { Label } from './components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './components/ui/select'
import { Separator } from './components/ui/separator'
import { Textarea } from './components/ui/textarea'
import { Wand2 } from 'lucide-react';
import { VideoInputForm } from './components/video-input-form'
import { PromptSelect } from './components/prompt-select'
import { TemperatureSlider } from './components/temperature-slider'
import { useState } from 'react'
import { useCompletion } from 'ai/react'

export function App() {
  const [videoId, setVideoId] = useState<string | null>(null)
  const [transcription, setTranscription] = useState<string>('')
  const [temperature, setTemperature] = useState(0.5)
  const {input, setInput, completion, handleInputChange, handleSubmit, isLoading } = useCompletion({
    api: `http://localhost:3333/ai/complete`,
    body: {
      videoId,
      temperature,
    },
    headers: {
      'Content-type': 'application/json',
    },
  })

  return (
    <div className='flex flex-col min-h-screen'>
      <header className='border-b flex items-center justify-between px-6 py-3'>Header</header>
      <main className='flex flex-1 gap-6 p-6'>
        <aside className='w-80 space-y-6'>
          <VideoInputForm onVideoUploaded={setVideoId} onTranscriptionChanged={setTranscription} />

          <Separator />

          <form className='space-y-6' onSubmit={handleSubmit}>
            <div className='space-y-2'>
              <Label>Pre-defined Prompts</Label>
              <PromptSelect onPromptSelected={setInput} />
            </div>

            <Separator />

            <div className='space-y-2'>
              <Label>Model</Label>
              <Select defaultValue='gpt3.5' disabled>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value='gpt3.5'>GPT 3.5-Turbo 16k</SelectItem>
                </SelectContent>
              </Select>
              <span className='block italic leading-relaxed text-muted-foreground text-xs'>
                You will can choose another models in the future
              </span>
            </div>

            <Separator />

            <TemperatureSlider onTemperatureChange={value => setTemperature(value)} />

            <Separator />

            <Button className='w-full' disabled={isLoading} type='submit'>
              Generate
              <Wand2 className='ml-2' size={16} />
            </Button>
          </form>
        </aside>

        <section
          className='flex flex-col flex-1 gap-4'
        >
          <div className='flex-1 gap-4 grid grid-rows-3'>
            <Textarea
              className='bg-indigo-500 cursor-not-allowed leading-relaxed p-4 resize-none whitespace-pre-wrap'
              placeholder='After convert your video into an audio, the generated transcription will be shown here...'
              value={transcription}
            />
            <Textarea
              className='leading-relaxed p-4 resize-none'
              onChange={handleInputChange}
              placeholder='Type your instructions for AI here or select on the side menu a pre-defined prompt (Title or Description)!'
              value={input}
            />
            <Textarea
              className='bg-indigo-900 cursor-not-allowed leading-relaxed p-4 resize-none'
              placeholder='The result generated by AI using the instructions above will be shown here...'
              readOnly
              value={completion}
            />
          </div>
          <p className='italic text-muted-foreground text-sm'>
            Remember: you can use the<code className='text-indigo-600'>
              {' {transcription} '}</code>variable in your prompt to add a transcription content to uploaded video!
          </p>
        </section>
      </main>
    </div >
  )
}
